name: 'Receptura akcji Dockera'
description: 'Pozdrów kogoś'
inputs:
  who-to-greet:
    description: 'Kogo pozdrowić'
    required: true
    default: 'Świecie'
outputs:
  answer:
    description: 'Odpowiedź na wszystko (zawsze 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}